### ISSUE TITLE
 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by jadiaz** [ycjcl868/alfred-npmjs#2]
Starting debug for 'NpmSearch'

```
[2018-03-26 21:02:16][ERROR: input.scriptfilter] Code 1: 21:02:16 workflow.py:2249 DEBUG    workflow version: 1.0.2
21:02:16 workflow.py:2462 DEBUG    update_data: None
21:02:16 workflow.py:2267 ERROR    'NoneType' object has no attribute 'read'
Traceback (most recent call last):
  File "/Users/racan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.32269DE4-9B2C-4C9A-9A6D-92B6E98E2ED3/workflow/workflow.py", line 2260, in run
    func(self)
  File "npm_workflow.py", line 63, in main
    data = wf.cached_data(query, functools.partial(queryPackage, query), max_age=MAX_AGE)
  File "/Users/racan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.32269DE4-9B2C-4C9A-9A6D-92B6E98E2ED3/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "npm_workflow.py", line 50, in queryPackage
    return web.get(url).json()
  File "/Users/racan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.32269DE4-9B2C-4C9A-9A6D-92B6E98E2ED3/workflow/web.py", line 271, in json
    return json.loads(self.content, self.encoding or 'utf-8')
  File "/Users/racan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.32269DE4-9B2C-4C9A-9A6D-92B6E98E2ED3/workflow/web.py", line 302, in content
    self._content = self.raw.read()
AttributeError: 'NoneType' object has no attribute 'read'
21:02:16 workflow.py:2290 DEBUG    workflow finished in 0.379 seconds
```

**Comment by yihou** [comment]
Met the same issue

**Comment by ycjcl868** [comment]
@jadiaz @yihou it works again.
